[workspace]
members = ["cli", "crypto/*", "mem_usage_benches"]

[workspace.package]
edition = "2024"
version = "0.1.3"

[workspace.dependencies]

# *** Internal Dependencies ***
bouncycastle = { path = "./" }
bouncycastle-base64 = { path = "./crypto/base64" }
bouncycastle-core = { path = "crypto/core" }
bouncycastle-core-test-framework = { path = "./crypto/core-test-framework" }
bouncycastle-ed = { path = "crypto/ed" }
bouncycastle-factory = { path = "./crypto/factory" }
bouncycastle-hex = { path = "./crypto/hex" }
bouncycastle-hkdf = { path = "./crypto/hkdf" }
bouncycastle-hmac = { path = "./crypto/hmac" }
bouncycastle-math = { path = "./crypto/math" }
bouncycastle-mlkem = { path = "./crypto/mlkem" }
bouncycastle-mlkem-lowmemory = { path = "./crypto/mlkem-lowmemory" }
bouncycastle-mldsa = { path = "./crypto/mldsa" }
bouncycastle-mldsa-lowmemory = { path = "./crypto/mldsa-lowmemory" }
bouncycastle-rng = { path = "./crypto/rng" }
bouncycastle-sha2 = { path = "./crypto/sha2" }
bouncycastle-sha3 = { path = "./crypto/sha3" }
bouncycastle-utils = { path = "./crypto/utils" }


# *** External Dependencies ***
criterion = "0.8.2" # only for benchmarking, not used in lib or cli build

[profile.release]
lto = "thin"
strip = "debuginfo"


# libbouncycastle
[package]
name = "bouncycastle"
version.workspace = true
edition.workspace = true

[dependencies]
bouncycastle-base64.workspace = true
bouncycastle-core.workspace = true
bouncycastle-ed.workspace = true
bouncycastle-factory.workspace = true
bouncycastle-hex.workspace = true
bouncycastle-hkdf.workspace = true
bouncycastle-hmac.workspace = true
bouncycastle-mldsa.workspace = true
bouncycastle-mldsa-lowmemory.workspace = true
bouncycastle-mlkem.workspace = true
bouncycastle-mlkem-lowmemory.workspace = true
bouncycastle-rng.workspace = true
bouncycastle-sha2.workspace = true
bouncycastle-sha3.workspace = true
