[package]
name = "bouncycastle-aes"
version.workspace = true
edition.workspace = true

[dependencies]
bouncycastle-core.workspace = true
bouncycastle-utils.workspace = true

[dev-dependencies]
bouncycastle-core-test-framework.workspace = true
bouncycastle-hex.workspace = true
serde_json = "1.0"

#[[bench]]
#name = "aes_benches"
#harness = false
