use bouncycastle_utils::ct::Condition;
use math::modular;

const M51: i64 = (1 << 51) - 1;

pub const P32: [u32; 8] = [
    0xFFFFFFED, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x7FFFFFFF,
];
pub const P64: [u64; 4] =
    [0xFFFFFFFFFFFFFFED, 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFFF];

// TODO Add magnitude, normalized fields to CoordField in debug mode and track validity through all operations
#[derive(Clone, Copy, Debug, Default)]
#[must_use]
#[repr(transparent)]
// TODO -- are all these annotations really necessary? Doesn't this contain secrets? Don't we want to block Debug?
// TODO -- should this be `[Secret<i64>; 5]` ?
// TODO -- why is this pub and not pub(crate)? -- same question for the fn's in the impl.
pub struct CoordField([i64; 5]);

// TODO -- all of these need at least simple unit tests
impl CoordField {
    /// Add another [`CoordField`] to this one, component-wise.
    pub const fn add(&self, rhs: &Self) -> Self {
        let [x0, x1, x2, x3, x4] = self.0;
        let [y0, y1, y2, y3, y4] = rhs.0;
        Self([x0 + y0, x1 + y1, x2 + y2, x3 + y3, x4 + y4])
    }

    // TODO -- needs a docstring
    pub const fn apm(&self, rhs: &Self) -> (Self, Self) {
        let [x0, x1, x2, x3, x4] = self.0;
        let [y0, y1, y2, y3, y4] = rhs.0;
        (
            Self([x0 + y0, x1 + y1, x2 + y2, x3 + y3, x4 + y4]),
            Self([x0 - y0, x1 - y1, x2 - y2, x3 - y3, x4 - y4]),
        )
    }

    // TODO -- why are we cloning?
    pub const fn add_one(&self) -> Self {
        let [x0, x1, x2, x3, x4] = self.0;
        Self([x0 + 1, x1, x2, x3, x4])
    }

    // TODO -- why are we returning the same ref we were passed?
    pub fn add_one_mut(&mut self) -> &mut Self {
        self.0[0] += 1;
        self
    }

    // TODO Requires normalized inputs
    // TODO -- what uses this?
    pub const fn are_equal(lhs: &Self, rhs: &Self) -> Condition<i64> {
        let [x0, x1, x2, x3, x4] = lhs.0;
        let [y0, y1, y2, y3, y4] = rhs.0;
        Condition::<i64>::is_zero((x0 ^ y0) | (x1 ^ y1) | (x2 ^ y2) | (x3 ^ y3) | (x4 ^ y4))
    }

    // TODO Requires normalized inputs
    // TODO -- what uses this?
    pub const fn are_equal_var(lhs: &Self, rhs: &Self) -> bool {
        Self::are_equal(lhs, rhs).to_bool_var()
    }

    // TODO -- needs a docstring
    pub const fn carry(&self) -> Self {
        let [x0, x1, x2, x3, x4] = self.0;
        let c1 = x0 >> 51;
        let c2 = x1 >> 51;
        let c3 = x2 >> 51;
        let c4 = x3 >> 51;
        let c5 = x4 >> 51;
        let z0 = (x0 & M51) + c5 * 19;
        let z1 = (x1 & M51) + c1;
        let z2 = (x2 & M51) + c2;
        let z3 = (x3 & M51) + c3;
        let z4 = (x4 & M51) + c4;
        Self([z0, z1, z2, z3, z4])
    }

    // TODO -- why are we returning the same ref we were passed?
    pub fn carry_mut(&mut self) -> &mut Self {
        *self = self.carry();
        self
    }

    /// Move the coordinates of x into self if `cond` is true.
    pub fn cmov(&mut self, cond: Condition<i64>, x: &Self) -> &mut Self {
        // *self = Self::cselect(cond, x, self);
        cond.mov(x.0[0], &mut self.0[0]);
        cond.mov(x.0[1], &mut self.0[1]);
        cond.mov(x.0[2], &mut self.0[2]);
        cond.mov(x.0[3], &mut self.0[3]);
        cond.mov(x.0[4], &mut self.0[4]);
        self
    }

    /// Negate the components of self if `cond` is true.
    pub fn cnegate(&mut self, cond: Condition<i64>) -> &mut Self {
        self.0[0] = cond.negate(self.0[0]);
        self.0[1] = cond.negate(self.0[1]);
        self.0[2] = cond.negate(self.0[2]);
        self.0[3] = cond.negate(self.0[3]);
        self.0[4] = cond.negate(self.0[4]);
        self
    }

    /// Returns a clone of lhs if `cond` is true, else returns rhs.
    pub fn cselect(cond: Condition<i64>, lhs: &Self, rhs: &Self) -> Self {
        let [x0, x1, x2, x3, x4] = lhs.0;
        let [y0, y1, y2, y3, y4] = rhs.0;
        let z0 = cond.select(x0, y0);
        let z1 = cond.select(x1, y1);
        let z2 = cond.select(x2, y2);
        let z3 = cond.select(x3, y3);
        let z4 = cond.select(x4, y4);
        Self([z0, z1, z2, z3, z4])
    }

    /// Swap the values of lhs and rhs if `cond` is true.
    pub fn cswap(cond: Condition<i64>, lhs: &mut Self, rhs: &mut Self) {
        (lhs.0[0], rhs.0[0]) = cond.swap(lhs.0[0], rhs.0[0]);
        (lhs.0[1], rhs.0[1]) = cond.swap(lhs.0[1], rhs.0[1]);
        (lhs.0[2], rhs.0[2]) = cond.swap(lhs.0[2], rhs.0[2]);
        (lhs.0[3], rhs.0[3]) = cond.swap(lhs.0[3], rhs.0[3]);
        (lhs.0[4], rhs.0[4]) = cond.swap(lhs.0[4], rhs.0[4]);
    }

    // TODO -- decide how the normalization precondition is handled across this codec group.
    //          This comment was generated by Claude and left here to be considered unce I have
    //          a better understanding of the code.
    //
    // `decode_255` deliberately returns an un-normalized value: RFC 7748 Section 5 requires that
    // non-canonical u-coordinates (u >= p) be accepted rather than rejected. But `encode_255`,
    // `encode64_255`, `are_equal`, `are_equal_var` and `parity` all *require* a normalized input,
    // enforced today only by a documented precondition that every call site has to remember. All of
    // them currently do (`scalar_mult` and `encode_u_coordinate` in x25519.rs, `inv` below), so this
    // is a latent footgun rather than a live bug -- but the asymmetry is ugly: decoding asks nothing
    // of the caller, encoding and comparison ask for a step they can silently omit. `parity` is the
    // sharpest edge: p is odd, so a value in [p, 2^255) reports the parity of v rather than v - p.
    //
    // Options:
    //  1. Fold `self.normalize()` into `encode_255` and drop it from its call sites. Free -- since
    //     normalize is idempotent this moves work rather than adding it -- and encode is outside the
    //     ladder loop, so nothing hot is touched. Does not help `are_equal`/`parity`, and folding it
    //     into `are_equal` WOULD cost, because that one can land in hot code.
    //  2. Typestate: `normalize(self) -> Normalized`, with `encode_255`, `are_equal` and `parity`
    //     defined only on `Normalized`. Compile-time enforcement, which is what
    //     QUALITY_AND_STYLE.md asks for over runtime discipline, and it covers the whole group at
    //     once. Bigger change, and it wants the full list of consumers -- Ed25519 point compression
    //     will add more -- so it probably waits for that (see the deferral note atop x25519.rs).
    //  3. Debug-only tracking, i.e. the magnitude/normalized fields already proposed in the TODO at
    //     the top of this file. Catches violations in tests without changing the API, but proves
    //     nothing in release and puts a debug-only field on a `Copy` type.
    //
    // None of these remove the precondition outright: `normalize` itself needs limbs inside the
    // magnitude bound that `reduce`'s carry chain assumes (`t5 * 19 + x0` must not overflow i64).
    // That residual bound is exactly what option 3 would track.

    /// Encodes a field element as a 255-bit value in 32 little-endian bytes; the inverse of [`Self::decode_255`].
    /// Bit 255 (the most significant bit of the last byte) is always written as zero.
    ///
    /// Callers that need that bit to carry something else -- the
    /// sign of x in an Ed25519 point encoding (Section 5.1.3 of RFC 8032) -- must OR it in after.
    ///
    /// Note: Requires normalized self -- see [`Self::encode64_255`]; only a normalized value encodes to the
    /// canonical byte string for its residue class.
    ///
    /// Input: self, normalized; a 32-byte output buffer.
    /// Output: The value written to `bytes` as a 255-bit little-endian integer.
    pub fn encode_255(&self, bytes: &mut [u8; 32]) {
        let [w0, w1, w2, w3] = self.encode64_255();
        let (a, b, c, d) = (w0.to_le_bytes(), w1.to_le_bytes(), w2.to_le_bytes(), w3.to_le_bytes());
        // Each word fills a fixed 8-byte window, least significant word first. Every index is a
        // constant into a fixed-size array, so an out-of-bounds index would be a compile error (the
        // deny-by-default `unconditional_panic` lint) and no runtime bounds check survives.
        *bytes = [
            a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], //
            b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], //
            c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7], //
            d[0], d[1], d[2], d[3], d[4], d[5], d[6], d[7],
        ];
    }

    /// Packs the five 51-bit limbs into a 255-bit little-endian integer held as four 64-bit words,
    /// each word taking a whole limb plus the low bits of the next. Inverse of
    /// [`Self::decode64_255`]. Bit 255 of the result is always zero, since limb `x4` lands in bits
    /// 204..254.
    ///
    /// Note: Requires normalized self: every limb must be in [0, 2^51) and the value reduced mod p.
    /// The splices below are `|`, not `+`, so a limb with bits at or above 51 collides with the next
    /// limb's bits instead of carrying into them, and the result is garbage. (The `x1 << 51` etc.
    /// deliberately shift bits off the top of the i64 -- those are the bits the previous word
    /// already carried.)
    ///
    /// Input: self, normalized.
    /// Output: The value as four little-endian 64-bit words, least significant word first.
    const fn encode64_255(&self) -> [u64; 4] {
        let [x0, x1, x2, x3, x4] = self.0;
        let z0 = (x0 | x1 << 51) as u64;
        let z1 = (x1 >> 13 | x2 << 38) as u64;
        let z2 = (x2 >> 26 | x3 << 25) as u64;
        let z3 = (x3 >> 39 | x4 << 12) as u64;
        [z0, z1, z2, z3]
    }

    /// Decodes a 32-byte little-endian encoding of a field element. Bit 255 (the most significant
    /// bit of the last byte) is masked off and ignored, since it is not part of a 255-bit field
    /// element. Callers own the meaning of that bit: for X25519 it is unused and masking it is
    /// required (see [`crate::x25519::decode_u_coordinate`]), for Ed25519 it carries the sign of x
    /// (Section 5.1.3 of RFC 8032) and must be stripped off and handled separately.
    /// Input: A 32-byte little-endian integer.
    /// Output: The low 255 bits of that integer as a [`CoordField`].
    ///
    /// Note: Result is NOT normalized -- the value is in [0, 2^255), so the 19 encodings of
    /// 2^255-19 .. 2^255-1 decode to values >= p. Call `normalize` before comparing or encoding.
    pub const fn decode_255(bytes: &[u8; 32]) -> Self {
        let b = bytes;
        let x0 = u64::from_le_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]]);
        let x1 = u64::from_le_bytes([b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15]]);
        let x2 = u64::from_le_bytes([b[16], b[17], b[18], b[19], b[20], b[21], b[22], b[23]]);
        let x3 = u64::from_le_bytes([b[24], b[25], b[26], b[27], b[28], b[29], b[30], b[31]]);
        Self::decode64_255(&[x0, x1, x2, x3])
    }

    /// Repacks a 256-bit little-endian integer held as four 64-bit words into the five 51-bit limbs
    /// of a [`CoordField`], where the represented value is
    /// `z0 + z1*2^51 + z2*2^102 + z3*2^153 + z4*2^204`. Each limb is a 51-bit window of the input,
    /// straddling word boundaries; the `& M51` masks make every limb non-negative and leave headroom
    /// for lazily-carried arithmetic. Bit 255 of the input is dropped -- see [`Self::decode_255`].
    /// Inverse of [`Self::encode64_255`].
    /// Input: A 256-bit integer as four little-endian 64-bit words, least significant word first.
    /// Output: Bits 0..254 of that integer as a [`CoordField`].
    ///
    /// Note: Result is NOT normalized -- see the note on [`Self::decode_255`].
    const fn decode64_255(x: &[u64; 4]) -> Self {
        let [x0, x1, x2, x3] = *x;
        let z0 = x0 as i64 & M51;
        let z1 = (x0 >> 51 | x1 << 13) as i64 & M51;
        let z2 = (x1 >> 38 | x2 << 26) as i64 & M51;
        let z3 = (x2 >> 25 | x3 << 39) as i64 & M51;
        let z4 = (x3 >> 12) as i64 & M51;
        Self([z0, z1, z2, z3, z4])
    }

    // TODO -- needs a docstring
    pub fn inv(&self) -> Self {
        // let (x2, t) = self.pow_p_sub5_div8();
        // t.sqr_n(3).mul(&x2)

        #[inline(always)]
        fn is_zero(x: &[u64; 4]) -> Condition<u64> {
            // todo -- we'll get this when we merge /pull/63 and then rebase this branch on top
            Condition::<u64>::is_zero(x[0] | x[1] | x[2] | x[3])
        }

        let u = self.normalize().encode64_255();
        let mut v = [0; 4];
        let success = modular::mod_odd_inverse(&P64, &u, &mut v);
        debug_assert!((success | (is_zero(&u) & is_zero(&v))).to_bool_var());
        Self::decode64_255(&v)
    }

    // TODO -- needs a docstring
    // TODO -- why are we returning the same ref we were passed?
    pub fn inv_mut(&mut self) -> &mut Self {
        *self = self.inv();
        self
    }

    // TODO -- needs a docstring
    pub fn inv_var(&self) -> Self {
        // TODO Use a vartime optimized version of modular::mod_odd_inverse
        self.inv()
    }

    // TODO -- needs a docstring
    // TODO -- why are we returning the same ref we were passed?
    pub fn inv_mut_var(&mut self) -> &mut Self {
        *self = self.inv_var();
        self
    }

    // TODO -- needs a docstring
    // TODO Requires normalized self
    pub const fn is_one(&self) -> Condition<i64> {
        let [x0, x1, x2, x3, x4] = self.0;
        let x0 = x0 ^ 1;
        Condition::<i64>::is_zero(x0 | x1 | x2 | x3 | x4)
    }

    // TODO -- needs a docstring
    // TODO Requires normalized self
    pub const fn is_one_var(&self) -> bool {
        self.is_one().to_bool_var()
    }

    // TODO -- needs a docstring
    // TODO Requires normalized self
    pub const fn is_zero(&self) -> Condition<i64> {
        let [x0, x1, x2, x3, x4] = self.0;
        Condition::<i64>::is_zero(x0 | x1 | x2 | x3 | x4)
    }

    // TODO -- needs a docstring
    // TODO Requires normalized self
    pub const fn is_zero_var(&self) -> bool {
        self.is_zero().to_bool_var()
    }

    // TODO -- needs a docstring
    pub const fn mul(&self, rhs: &Self) -> Self {
        #[inline(always)]
        const fn m(x: i64, y: i64) -> i128 {
            x as i128 * y as i128
        }

        let [x0, x1, x2, x3, x4] = self.0;
        let [y0, y1, y2, y3, y4] = rhs.0;
        let [t1, t2, t3, t4] = [y1 * 19, y2 * 19, y3 * 19, y4 * 19];

        Self::reduce_products(
            m(x0, y0) + m(x1, t4) + m(x2, t3) + m(x3, t2) + m(x4, t1),
            m(x0, y1) + m(x1, y0) + m(x2, t4) + m(x3, t3) + m(x4, t2),
            m(x0, y2) + m(x1, y1) + m(x2, y0) + m(x3, t4) + m(x4, t3),
            m(x0, y3) + m(x1, y2) + m(x2, y1) + m(x3, y0) + m(x4, t4),
            m(x0, y4) + m(x1, y3) + m(x2, y2) + m(x3, y1) + m(x4, y0),
        )
    }

    // TODO -- needs a docstring
    pub const fn mul_u32(&self, rhs: u32) -> Self {
        #[inline(always)]
        const fn m(x: i64, y: i64) -> i128 {
            x as i128 * y as i128
        }

        let [x0, x1, x2, x3, x4] = self.0;
        let y0 = rhs as i64;

        Self::reduce_products(m(x0, y0), m(x1, y0), m(x2, y0), m(x3, y0), m(x4, y0))
    }

    /// Negates the components of self
    pub const fn negate(&self) -> Self {
        let [x0, x1, x2, x3, x4] = self.0;
        Self([-x0, -x1, -x2, -x3, -x4])
    }

    pub fn negate_mut(&mut self) -> &mut Self {
        *self = self.negate();
        self
    }

    // TODO Module consumers should instead have a method to construct from [u64; 4] (or indeed a Nat<4>)
    pub const fn new(x0: i64, x1: i64, x2: i64, x3: i64, x4: i64) -> Self {
        Self([x0, x1, x2, x3, x4])
    }

    pub const fn normalize(&self) -> Self {
        let y = (self.0[4] >> (51 - 1)) & 1;
        self.reduce(y).reduce(-y)
    }

    pub fn normalize_mut(&mut self) -> &mut Self {
        *self = self.normalize();
        self
    }

    pub const fn one() -> Self {
        Self([1, 0, 0, 0, 0])
    }

    // TODO Better name -- is_odd() ?
    pub const fn parity(&self) -> u8 {
        (self.0[0] & 1) as u8
    }

    // TODO Addition chain macro/function
    const fn pow_p_sub5_div8(&self) -> (Self, Self) {
        // TODO -- where is this from?
        // z = x^((p-5)/8) = x^FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD
        // (250 1s) (1 0s) (1 1s)
        // Addition chain: [1] 2 3 5 10 15 25 50 75 125 [250]

        let x = self;
        let x2 = x.sqr().mul(x);
        let x3 = x2.sqr().mul(x);
        let x5 = x3.sqr_n(2).mul(&x2);
        let x10 = x5.sqr_n(5).mul(&x5);
        let x15 = x10.sqr_n(5).mul(&x5);
        let x25 = x15.sqr_n(10).mul(&x10);
        let x50 = x25.sqr_n(25).mul(&x25);
        let x75 = x50.sqr_n(25).mul(&x25);
        let x125 = x75.sqr_n(50).mul(&x50);
        let x250 = x125.sqr_n(125).mul(&x125);

        let z = x250.sqr_n(2).mul(x);
        (x2, z)
    }

    // TODO -- what is this and where is it from?
    const fn reduce(&self, y: i64) -> Self {
        let [x0, x1, x2, x3, x4] = self.0;

        let t4 = x4 & M51;
        let t5 = (x4 >> 51) + y;

        let mut c = t5 * 19;

        c += x0;
        let z0 = c & M51;
        c >>= 51;
        c += x1;
        let z1 = c & M51;
        c >>= 51;
        c += x2;
        let z2 = c & M51;
        c >>= 51;
        c += x3;
        let z3 = c & M51;
        c >>= 51;
        c += t4;
        let z4 = c;

        Self([z0, z1, z2, z3, z4])
    }

    // TODO -- what is this and where is it from?
    #[inline]
    const fn reduce_products(p0: i128, p1: i128, p2: i128, p3: i128, p4: i128) -> Self {
        #[inline(always)]
        const fn split(x: i128) -> (i64, i64) {
            (x as i64 & M51, (x >> 51) as i64)
        }

        let (t0, c1) = split(p0);
        let (t1, c2) = split(p1);
        let (t2, c3) = split(p2);
        let (t3, c4) = split(p3);
        let (t4, c5) = split(p4 + c4 as i128);

        let u0 = t0 + c5 * 19;
        let u1 = t1 + c1;
        let u2 = t2 + c2;
        let u3 = t3 + c3;

        Self([
            u0 & M51,
            (u1 & M51) + (u0 >> 51),
            (u2 & M51) + (u1 >> 51),
            (u3 & M51) + (u2 >> 51),
            t4 + (u3 >> 51),
        ])
    }

    // TODO -- what is this and where is it from?
    // TODO -- why is it pub and now pub(crate)
    pub const fn sqr(&self) -> Self {
        #[inline(always)]
        const fn m(x: i64, y: i64) -> i128 {
            x as i128 * y as i128
        }

        let [x0, x1, x2, x3, x4] = self.0;
        let [y0, y1, y2, y3] = [x0 * 2, x1 * 2, x2 * 2, x3 * 2];
        let [t3, t4] = [x3 * 19, x4 * 19];

        Self::reduce_products(
            m(x0, x0) + m(y1, t4) + m(y2, t3),
            m(y0, x1) + m(y2, t4) + m(x3, t3),
            m(y0, x2) + m(x1, x1) + m(y3, t4),
            m(y0, x3) + m(y1, x2) + m(x4, t4),
            m(y0, x4) + m(y1, x3) + m(x2, x2),
        )
    }

    // TODO -- what is this and where is it from?
    // TODO -- why is it pub and now pub(crate)
    pub fn sqr_mut(&mut self) -> &mut Self {
        *self = self.sqr();
        self
    }

    // TODO -- what is this and where is it from?
    // TODO -- why is it pub and now pub(crate)
    pub const fn sqr_n(&self, mut n: usize) -> Self {
        let mut z = *self;
        while n > 0 {
            z = z.sqr();
            n -= 1;
        }
        z
    }

    // TODO -- what is this and where is it from?
    // TODO -- why is it pub and now pub(crate)
    pub const fn sqrt_ratio_var(u: &Self, v: &Self) -> Option<Self> {
        let uv = u.mul(v);
        let v2 = v.sqr();
        let uv3 = v2.mul(&uv);
        let uv7 = v2.sqr().mul(&uv3);

        let (_, w) = uv7.pow_p_sub5_div8();
        let x = w.mul(&uv3);
        let vx2 = x.sqr().mul(v);

        let t = vx2.sub(u).normalize();

        // TODO -- is this doing a conditional on a secret value?
        if t.is_zero_var() {
            return Some(x);
        }

        let t = vx2.add(u).normalize();
        if t.is_zero_var() {
            const ROOT_NEG_ONE: CoordField = CoordField([
                -0x0001E4D8B5F15F50, 0x0000D5A5FC8F189E, -0x000010A16342F3A0, -0x00007A6A597FB361,
                0x0002B8324804FC1E,
            ]);

            return Some(x.mul(&ROOT_NEG_ONE));
        }

        None
    }

    /// Subtract rhs from self, component-wise.
    // TODO -- why is this pub and not pub(crate) ?
    // TODO -- how does this handle wrapping / overflow?
    pub const fn sub(&self, rhs: &Self) -> Self {
        let [x0, x1, x2, x3, x4] = self.0;
        let [y0, y1, y2, y3, y4] = rhs.0;
        Self([x0 - y0, x1 - y1, x2 - y2, x3 - y3, x4 - y4])
    }

    /// Subtract CoordField::One from self, component-wise, and return a new CoordField.
    // TODO -- why is this pub and not pub(crate) ?
    // TODO -- how does this handle wrapping / overflow?
    pub const fn sub_one(&self) -> Self {
        let [x0, x1, x2, x3, x4] = self.0;
        Self([x0 - 1, x1, x2, x3, x4])
    }

    /// Subtract CoordField::One from self, component-wise, in-place.
    // TODO -- do we really need both versions of this?
    // TODO -- why is this pub and not pub(crate) ?
    // TODO -- how does this handle wrapping / overflow?
    pub fn sub_one_mut(&mut self) -> &mut Self {
        self.0[0] -= 1;
        self
    }

    pub const fn zero() -> Self {
        Self([0; 5])
    }
}

// TODO -- at least a basic unit test for each math function

// TODO --  from RFC7748 s. 5:
//      u-coordinate array:
//          When receiving such an array, implementations of X25519
//    (but not X448) MUST mask the most significant bit in the final byte.
//    This is done to preserve compatibility with point formats that
//    reserve the sign bit for use in other protocols and to increase
//    resistance to implementation fingerprinting.
//

// TODO --  from RFC7748 s. 5:
//      Implementations MUST accept non-canonical values and process them as
//    if they had been reduced modulo the field prime.  The non-canonical
//    values are 2^255 - 19 through 2^255 - 1 for X25519 and 2^448 - 2^224
//    - 1 through 2^448 - 1 for X448.

#[cfg(test)]
mod curve25519_tests {
    use super::*;

    /// Alice's public key from the X25519 test vector in Section 6.1 of RFC 7748, used here purely
    /// as a fixed value for the byte <-> limb codec. It is less than p (its top byte is 0x6A), so
    /// its encoding is canonical and it needs no normalization to round-trip exactly.
    const KNOWN_VALUE: [u8; 32] = [
        0x85, 0x20, 0xF0, 0x09, 0x89, 0x30, 0xA7, 0x54, //
        0x74, 0x8B, 0x7D, 0xDC, 0xB4, 0x3E, 0xF7, 0x5A, //
        0x0D, 0xBF, 0x3A, 0x0D, 0x26, 0x38, 0x1A, 0xF4, //
        0xEB, 0xA4, 0xA9, 0x8E, 0xAA, 0x9B, 0x4E, 0x6A,
    ];

    /// The same value as five 51-bit limbs: `KNOWN_LIMBS[i] == (v >> (51 * i)) & (2^51 - 1)`, where
    /// v is `KNOWN_VALUE` read as a little-endian integer. Computed independently of this crate.
    const KNOWN_LIMBS: [i64; 5] =
        [0x7308909F02085, 0x69B8FB16E8A94, 0x4EAFC356BDCFA, 0x275FA0D1C1306, 0x6A4E9BAA8EA9A];

    #[test]
    fn decode_255_known_value() {
        assert_eq!(CoordField::decode_255(&KNOWN_VALUE).0, KNOWN_LIMBS);

        // Bit 255 is not part of the field element, so setting it must not change the result.
        let mut bit_255_set = KNOWN_VALUE;
        bit_255_set[31] |= 0x80;
        assert_eq!(CoordField::decode_255(&bit_255_set).0, KNOWN_LIMBS);
    }

    #[test]
    fn encode_255_known_value() {
        // Start from a non-zero buffer so a partial write cannot pass by accident.
        let mut bytes = [0xFF_u8; 32];
        CoordField(KNOWN_LIMBS).encode_255(&mut bytes);
        assert_eq!(bytes, KNOWN_VALUE);
    }
}
